using System.Collections.Generic;
using System.Text.Json.Serialization;
using Taix.Client.Shared.Models;
using Taix.Client.Shared.Models.Config;
using Taix.Client.Shared.Models.Data;
using Taix.Client.Shared.Models.Db;

namespace Taix.Client.Librarys.Api;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(ApiResponse))]
[JsonSerializable(typeof(ApiResponse<AppModel>))]
[JsonSerializable(typeof(ApiResponse<List<AppModel>>))]
[JsonSerializable(typeof(ApiResponse<CategoryModel>))]
[JsonSerializable(typeof(ApiResponse<List<CategoryModel>>))]
[JsonSerializable(typeof(ApiResponse<DailyLogModel>))]
[JsonSerializable(typeof(ApiResponse<List<DailyLogModel>>))]
[JsonSerializable(typeof(ApiResponse<HoursLogModel>))]
[JsonSerializable(typeof(ApiResponse<List<HoursLogModel>>))]
[JsonSerializable(typeof(ApiResponse<AppSessionModel>))]
[JsonSerializable(typeof(ApiResponse<List<AppSessionModel>>))]
[JsonSerializable(typeof(ApiResponse<double[]>))]
[JsonSerializable(typeof(ApiResponse<int>))]
[JsonSerializable(typeof(ApiResponse<WebSiteModel>))]
[JsonSerializable(typeof(ApiResponse<List<WebSiteModel>>))]
[JsonSerializable(typeof(ApiResponse<WebSiteCategoryModel>))]
[JsonSerializable(typeof(ApiResponse<List<WebSiteCategoryModel>>))]
[JsonSerializable(typeof(ApiResponse<ColumnDataModel>))]
[JsonSerializable(typeof(ApiResponse<List<ColumnDataModel>>))]
[JsonSerializable(typeof(ApiResponse<ExportDataResult>))]
[JsonSerializable(typeof(ApiResponse<InfrastructureDataModel>))]
[JsonSerializable(typeof(ApiResponse<List<InfrastructureDataModel>>))]
[JsonSerializable(typeof(ApiResponse<WebBrowseLogModel>))]
[JsonSerializable(typeof(ApiResponse<List<WebBrowseLogModel>>))]
[JsonSerializable(typeof(ApiResponse<WebExportDataResult>))]
[JsonSerializable(typeof(ApiResponse<ConfigModel>))]
[JsonSerializable(typeof(AppModel))]
[JsonSerializable(typeof(List<AppModel>))]
[JsonSerializable(typeof(CategoryModel))]
[JsonSerializable(typeof(List<CategoryModel>))]
[JsonSerializable(typeof(DailyLogModel))]
[JsonSerializable(typeof(List<DailyLogModel>))]
[JsonSerializable(typeof(HoursLogModel))]
[JsonSerializable(typeof(List<HoursLogModel>))]
[JsonSerializable(typeof(AppSessionModel))]
[JsonSerializable(typeof(List<AppSessionModel>))]
[JsonSerializable(typeof(double[]))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(WebSiteModel))]
[JsonSerializable(typeof(List<WebSiteModel>))]
[JsonSerializable(typeof(WebSiteCategoryModel))]
[JsonSerializable(typeof(List<WebSiteCategoryModel>))]
[JsonSerializable(typeof(ColumnDataModel))]
[JsonSerializable(typeof(List<ColumnDataModel>))]
[JsonSerializable(typeof(InfrastructureDataModel))]
[JsonSerializable(typeof(List<InfrastructureDataModel>))]
[JsonSerializable(typeof(WebBrowseLogModel))]
[JsonSerializable(typeof(List<WebBrowseLogModel>))]
[JsonSerializable(typeof(WebExportDataResult))]
[JsonSerializable(typeof(UpdateAppDurationRequest))]
[JsonSerializable(typeof(CreateAppRequest))]
[JsonSerializable(typeof(UpdateAppRequest))]
[JsonSerializable(typeof(CreateCategoryRequest))]
[JsonSerializable(typeof(UpdateCategoryRequest))]
[JsonSerializable(typeof(AddUrlBrowseTimeRequest))]
[JsonSerializable(typeof(int[]))]
[JsonSerializable(typeof(UpdateSitesCategoryRequest))]
[JsonSerializable(typeof(ConfigModel))]
[JsonSerializable(typeof(GeneralModel))]
[JsonSerializable(typeof(BehaviorModel))]
[JsonSerializable(typeof(BehaviorModel))]
[JsonSerializable(typeof(List<string>))]
internal partial class TaixApiJsonContext : JsonSerializerContext { }
