    namespace Taix.Client.Controls.Base;

public class IconConverter
{
    public static string ToUnicode(IconTypes iconType) => iconType switch
    {
        IconTypes.None => string.Empty,
        IconTypes.Accept => "\xe8fb",
        IconTypes.Apps => "\xed35",
        IconTypes.ArrowDown8 => "\xf0ae",
        IconTypes.ArrowUp8 => "\xf0ad",
        IconTypes.Back => "\xe72b",
        IconTypes.BulletedList => "\xe8fd",
        IconTypes.CalculatorAddition => "\xe948",
        IconTypes.Calendar => "\xe787",
        IconTypes.Cancel => "\xe711",
        IconTypes.CaretDownSolid8 => "\xeddc",
        IconTypes.CaretUpSolid8 => "\xeddb",
        IconTypes.ChevronDown => "\xe70d",
        IconTypes.ChevronDownMed => "\xe972",
        IconTypes.ChevronLeft => "\xe76b",
        IconTypes.ChevronRight => "\xe76c",
        IconTypes.ChevronRightMed => "\xe974",
        IconTypes.ChevronUp => "\xe70e",
        IconTypes.ChevronUpMed => "\xe971",
        IconTypes.ChromeClose => "\xe8bb",
        IconTypes.ChromeMaximize => "\xe922",
        IconTypes.ChromeMinimize => "\xe921",
        IconTypes.ChromeRestore => "\xe923",
        IconTypes.DateTimeMirrored => "\xee93",
        IconTypes.Delete => "\xe74d",
        IconTypes.Error => "\xe783",
        IconTypes.Folder => "\xe8b7",
        IconTypes.FolderFill => "\xe8d5",
        IconTypes.FourBars => "\xe908",
        IconTypes.Home => "\xe80f",
        IconTypes.HomeSolid => "\xea8a",
        IconTypes.ImportantBadge12 => "\xedb1",
        IconTypes.IncidentTriangle => "\xe814",
        IconTypes.Info => "\xe946",
        IconTypes.More => "\xe712",
        IconTypes.OEM => "\xe74c",
        IconTypes.Photo => "\xe91b",
        IconTypes.Remove => "\xe738",
        IconTypes.ReportDocument => "\xe9f9",
        IconTypes.ScreenTime => "\xf182",
        IconTypes.Search => "\xe721",
        IconTypes.SearchAndApps => "\xe773",
        IconTypes.SetlockScreen => "\xe7b5",
        IconTypes.Settings => "\xe713",
        IconTypes.SettingsSolid => "\xf8b0",
        IconTypes.Share => "\xe72d",
        IconTypes.StatusCircleBlock => "\xf140",
        IconTypes.StockUp => "\xeb0f",
        IconTypes.Stopwatch => "\xe916",
        IconTypes.SubtractBold => "\xf8ab",
        IconTypes.WebSearch => "\xf6fa",
        IconTypes.Website => "\xeb41",
        IconTypes.ZeroBars => "\xe904",
        _ => string.Empty
    };
}
