namespace Taix.Client.Controls.Base;

/// <summary>
/// 图标类型
/// </summary>
public enum IconTypes
{
    None,
    Accept,
    Apps,
    ArrowDown8,
    ArrowUp8,
    Back,
    BulletedList,
    CalculatorAddition,
    Calendar,
    Cancel,
    CaretDownSolid8,
    CaretUpSolid8,
    ChevronDown,
    ChevronDownMed,
    ChevronLeft,
    ChevronRight,
    ChevronRightMed,
    ChevronUp,
    ChevronUpMed,
    ChromeClose,
    ChromeMaximize,
    ChromeMinimize,
    ChromeRestore,
    DateTimeMirrored,
    Delete,
    Error,
    Folder,
    FolderFill,
    FourBars,
    Home,
    HomeSolid,
    ImportantBadge12,
    IncidentTriangle,
    Info,
    More,
    OEM,
    Photo,
    Remove,
    ReportDocument,
    ScreenTime,
    Search,
    SearchAndApps,
    SetlockScreen,
    Settings,
    SettingsSolid,
    Share,
    StatusCircleBlock,
    StockUp,
    Stopwatch,
    SubtractBold,
    WebSearch,
    Website,
    ZeroBars
}
