export const CONFIG = {
  WS_URL: 'ws://127.0.0.1:8908/TaiWebSentry',
  HEARTBEAT_INTERVAL_MIN: 0.5,
  SAVE_INTERVAL_MIN: 0.5,
  RENOTIFY_INTERVAL_MIN: 0.5,
  RECONNECT_FAIL_SLEEP: 5,
  URL_CHANGE_DEBOUNCE_MS: 300,
  MAX_FAIL_QUEUE_SIZE: 100,
};